Redesign update with detections to match detections with tracker
roboflow/supervision pull request #1034
Opened 2024-03-23 04:27 UTC by rolson24

# Description

This change addresses this issue: (https://github.com/roboflow/supervision/issues/754)
`update_with_detections` now returns the original detections that were tracked by ByteTrack with their original bboxes, masks, class_ids, data fields and with updated track_ids. Detections that were not tracked this frame are not included in the returned detections.

## Type of change

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality) - Segmentation tracking

## How has this change been tested, please provide a testcase or example of how you tested the change?

I have tested this change by running object tracking for both object detection and segmentation in this [colab notebook](https://colab.research.google.com/drive/1azgc_A-divM3Z5l0TyHW2SRHnw6EUlbO?usp=sharing)

![segmentation_tracking](https://github.com/roboflow/supervision/assets/99894460/64a4ba95-6c43-4a2c-8f32-b74604023868)

## Any specific deployment considerations

Tracking docs should be updated to reflect that ByteTrack can now do segmentation tracking.

## Docs

-   [ ] Docs updated? What were the changes:

2024-03-23 04:28 UTC, rolson24 commented
Sorry about the number of commits. I tried to squash some together but messed up a bit. I can delete and resubmit if you need me to.

2024-03-23 18:06 UTC, SkalskiP requested changes

2024-03-23 18:06 UTC, SkalskiP commented on supervision/tracker/byte_tracker/core.py
> +            det_tlbrs = np.asarray([det[:4] for det in tensors])
Let's not use abbreviations. They make the code harder to read. To be honest I don't know what `det_tlbrs` or `track_tlbrs` means :)

2024-03-23 18:14 UTC, SkalskiP commented
Hi, @rolson24 👋🏻 ! Thanks a lot for this PR. I left a few comments (nothing serious). I would also like you to open a new PR with just one commit (if possible). I can use `Squash and merge` option but I'm not sure if GitHub will assign this commit to you :/ And I would want to give you credit for this work.

2024-03-23 23:52 UTC, rolson24 commented
Great! I made those changes and can submit a new PR.
Before I do though, I am wondering if we should add a method to the STrack class to get the actual bounding box from the detection that was used to update the track. Right now STrack.tlbr returns the predicted value of the bounding box. This means that when we do the matching in the update_with_detections from the original detections to the tracks, the wrong track might be matched to the original bounding box when there are two detections that are really close together. This won't matter for tracking performance, but it technically might return the wrong original detection in that frame. This also will allow us to not use the linear assignment function (in-efficient) and instead just search for the ious that are 1.0 because the original detections will match perfectly with the detections we get from the tracks.

2024-03-25 14:53 UTC, SkalskiP commented
Hi @rolson24 👋🏻 ! Awesome! In this case, I'll close this PR, and we will focus on https://github.com/roboflow/supervision/pull/1035. Thanks for being so cooperative 🙏🏻

2024-03-25 14:53 UTC, closed without merging