Enhanced from_transformers to support class name extraction
roboflow/supervision pull request #1046
Opened 2024-03-25 19:24 UTC by jeslinpjames

# Description

Issue #1043

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

Here is the  [Colab link](https://colab.research.google.com/drive/1xFjqajv-CU57SMF3r8niGaO2IjiGqJou?usp=sharing) with the changes made to the `from_transformers()` function.

## Any specific deployment considerations

For example, documentation changes, usability, usage/costs, secrets, etc.

## Docs

-   [x] Docs updated? What were the changes:
- The documentation for the `from_transformers` function has been updated to include the new parameter `id2label`.

2024-03-25 23:21 UTC, SkalskiP requested changes

2024-03-25 23:21 UTC, SkalskiP commented on supervision/detection/core.py
> +        cls, transformers_results: dict, id2label: Dict[int, str]
Could we make `id2label` `Optional` and make it `None` by default?

2024-03-25 23:21 UTC, SkalskiP commented on supervision/detection/core.py
> +            data={CLASS_NAME_DATA_FIELD: class_names},
And only add `CLASS_NAME_DATA_FIELD` field to `data` if `id2label` is not `None`.

2024-03-25 23:22 UTC, SkalskiP commented
Hi @jeslinpjames 👋🏻 I only left two minor comments.

2024-03-26 01:32 UTC, jeslinpjames commented
Hey @SkalskiP 👋🏻 Thanks for the review! I'll handle those minor adjustments immediately.

2024-03-28 16:57 UTC, SkalskiP commented
Hi @jeslinpjames 👋🏻 Thanks a lot for the update. We've also been simultaneously working on another feature related to this part of the code. Could you resolve the conflicts that have arisen?

2024-03-28 19:54 UTC, SkalskiP requested changes

2024-03-28 19:54 UTC, SkalskiP commented on supervision/detection/core.py
> +            class_id=transformers_results["labels"].cpu().detach().numpy().astype(int),
It looks like you forgot to add a data field in this line.

2024-03-28 19:54 UTC, SkalskiP commented
@jeslinpjames I left one more comment. :)

2024-03-28 19:57 UTC, jeslinpjames commented
Hey @SkalskiP, I've gone ahead and resolved the conflicts that arose in the `form_transformers` function. Would you mind reviewing it to ensure that the changes are okay?

2024-03-28 20:20 UTC, jeslinpjames commented
Hey @SkalskiP I've committed the changes. Could you please take a look and let me know if any further adjustments are needed?

2024-04-02 11:28 UTC, LinasKo requested changes
Hi @jeslinpjames 👋🏻

Well done with the implementation - I have very

2024-04-02 11:28 UTC, LinasKo commented on supervision/detection/core.py
> +            id2label (Dict[int, str]): A dictionary mapping class IDs to class names.
The docstring should also flag `id2label` as `Optional`.

Similar function: `from_azure_analyze_image`

2024-04-02 11:28 UTC, LinasKo commented on supervision/detection/core.py
>          masks = transformers_results["masks"].cpu().detach().numpy().astype(bool)
While we're at it, let's make the code more defensive.

I've reviewed the [image_processing_detr.py](https://github.com/huggingface/transformers/blob/fed27ffc7ec62837dca9bbfc83442eb3678ee026/src/transformers/models/detr/image_processing_detr.py#L744) in `transformers` and it turns out, with instance or panoptic segmentation `transformers_results` might not have `boxes`, `masks` or `labels`.

Let's add an `elif "masks" in transformers_results:` here and at the end - `raise NotImplementedError("Only object detection and semantic segmentation results are supported")`.

2024-04-02 12:08 UTC, SkalskiP commented
Hi @jeslinpjames 👋🏻 @LinasKo added some good comments. I would be very grateful if you could incorporate these changes, and then we'll be ready to merge.

2024-04-02 13:29 UTC, jeslinpjames commented
@LinasKo Thanks for the feedback! I've made the requested changes to the docstring and added the defensive code for masks in `transformers_results`. Could you please review it to ensure everything is okay or if any further adjustments are needed? Thanks!

2024-04-02 14:51 UTC, SkalskiP commented
@LinasKo, let me know if we are ready ;)

2024-04-02 15:00 UTC, LinasKo approved these changes
Looks good to me!
Happy to merge in.

2024-04-05 10:12 UTC, SkalskiP commented
Hi @jeslinpjames and @LinasKo 👋🏻 I made small docs improvements and tested the code. Looks good!

2024-04-05 10:12 UTC, SkalskiP approved these changes

2024-04-05 10:12 UTC, merged