Add segmentation model support to from_transformers
roboflow/supervision pull request #1054
Opened 2024-03-26 18:24 UTC by Griffin-Sullivan

# Description

Please include a summary of the change and which issue is fixed or implemented. Please also include relevant motivation and context (e.g. links, docs, tickets etc.).

List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

YOUR_ANSWER

## Any specific deployment considerations

For example, documentation changes, usability, usage/costs, secrets, etc.

## Docs

-   [ ] Docs updated? What were the changes:

2024-03-26 18:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/roboflow/supervision?pullRequest=1054) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/roboflow/supervision?pullRequest=1054) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/roboflow/supervision?pullRequest=1054) it.</sub>

2024-03-26 19:58 UTC, SkalskiP requested changes

2024-03-26 19:58 UTC, SkalskiP commented on supervision/detection/core.py
> +            masks = transformers_results["masks"].cpu().numpy()
I played around with your code in Colab, and this one change makes MaskAnnotator display the results as expected. Please double-check this. :)

![download - 2024-03-26T205109 264](https://github.com/roboflow/supervision/assets/26109316/2688511e-1973-4314-b1a5-d9b7f630c9cf)

2024-03-26 20:04 UTC, SkalskiP commented
Hi @Griffin-Sullivan 👋🏻 Thanks for your interest in supervision and time preparing this PR and Colab.

1. Please accept the CLA. Click the yellow button above and follow the instructions. 
2. I left a comment with suggested changes that will (most likely) solve your issue.

2024-03-26 21:08 UTC, Griffin-Sullivan commented
Ok I updated everything and it seemed to work fine. Let me know if there's any way we can improve this.

2024-03-28 13:39 UTC, SkalskiP approved these changes

2024-03-28 13:40 UTC, merged

2024-03-28 13:40 UTC, SkalskiP commented
@Griffin-Sullivan This is awesome! I'll update our docs page to include information about segmentation models being supported.