Add semantic segmentation polygon loading from Roboflow
roboflow/supervision pull request #110
Opened 2023-05-23 11:04 UTC by capjamesg

# Description

This PR adds support for loading the `points` values from Roboflow API detections into segmentation masks.

## Type of change

-   [X] New feature (non-breaking change which adds functionality)

## How has this change been tested, please provide a testcase or example of how you tested the change?

This code is used in `cvevals` for ingesting masks.

2023-05-23 11:40 UTC, SkalskiP commented
Adding some unit tests for `from_roboflow` would be awesome 😎

2023-05-23 11:40 UTC, SkalskiP requested changes

2023-05-23 11:40 UTC, SkalskiP commented on supervision/detection/core.py
> +                mask = np.zeros((int(height), int(width)), dtype=np.uint8)
Most of that logic can be replaced with `polygon_to_mask` function that can create a mask given `polygon`. Please use it. You can find it in `supervision.detection.utils`.

2023-05-23 11:40 UTC, SkalskiP commented on supervision/detection/core.py
> +        if len(mask) > 0:
Let's keep a single return and make it a bit more compact:

```python
return Detections(
    xyxy=np.array(xyxy),
    confidence=np.array(confidence),
    class_id=np.array(class_id).astype(int),
    mask=mask if mask else None,
)
```

2023-05-23 11:40 UTC, SkalskiP commented on supervision/detection/core.py
> +                mask=np.array(mask),
Make sure that type of mask is `dtype=bool`.

2023-05-23 11:40 UTC, SkalskiP commented on supervision/detection/core.py
> +            if prediction.get("points"):
Let's prevent adding indented logic - reverse the logical condition and use `continue`.

```python
if "points" not in prediction:
    continue
```

2023-05-31 11:20 UTC, capjamesg commented
@SkalskiP I have incorporated your feedback in my last commit. Please review. I have not added a test case, however.

2023-06-05 09:02 UTC, SkalskiP commented
@capjamesg do you have some code that I could use to test that code?

2023-06-14 14:40 UTC, merged