More flexibility in Detections.merge
roboflow/supervision pull request #1177
Opened 2024-05-08 12:26 UTC by LinasKo

# Description

* `Detections.merge` now merges detections when some of them are `None` or empty.
* Missing keys in `data` should not be an issue, unless further detections containing new data in those.
* Expanded tests with the new behaviour.

See the tests to see expected behaviour.

## Type of change

Please delete options that are not relevant.

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

:notebook:  [Google Colab](https://colab.research.google.com/drive/1PQ3j_5hAbuh4ivHEsQV8sxKvIVDGK7j7?usp=sharing)
* (Slicer with segmentation model still fails, but with a different error)
* Roboflow model (with `data` is now merged with `Detections.empty` successfully).
* Multiple new tests were written - all pass.

## Any specific deployment considerations

None

## Docs

-   [ ] Docs updated? What were the changes:

2024-05-08 14:43 UTC, SkalskiP requested changes

2024-05-08 14:43 UTC, SkalskiP commented on supervision/detection/utils.py
> +    key_set = set()
This variable is unused.

2024-05-08 14:43 UTC, SkalskiP commented on supervision/detection/utils.py
> +    # Naively merging entries and then validating length comes with a problem:
Please remove the comment. Comments are allowed only when we are doing something non-standard, such as a hack that is very non-obvious. Writing comments that describe the code is a bad practice.

Use variable and function names, as well as unit tests, to make the code more self-descriptive.

2024-05-08 14:43 UTC, SkalskiP commented on supervision/detection/utils.py
> +    sum_lengths = {}  # Validation. More useful than set for error message
Please remove the comments.

2024-05-08 14:43 UTC, SkalskiP commented on supervision/detection/utils.py
> +    for data in data_list:
Please limit the amount of indentions here. 
Two levels are okay, three is usually too many. An if inside an if, inside a for, inside another for is definitely too much. No wonder you had to add a comment explaining what's going on here. :)

2024-05-09 07:33 UTC, LinasKo commented
@SkalskiP, resolved as requested. Ready for review.

2024-05-10 13:40 UTC, SkalskiP approved these changes

2024-05-10 13:40 UTC, merged