fix: 🐞 yolo obb condition check set or for newer and older version
roboflow/supervision pull request #1222
Opened 2024-05-22 17:22 UTC by onuralpszr

### Description 

It fixes #1219.

We added "obb" key check added in #1093 and latest ultralytics package does not have that key.  I changed to "obb" check "and" to "or" and I tested with obb/detection/seg  all of them works.

2024-05-22 20:02 UTC, LinasKo requested changes

2024-05-22 20:08 UTC, onuralpszr commented on supervision/detection/core.py
> +        if "obb" in ultralytics_results or ultralytics_results.obb is not None:
@LinasKo good catch, true

2024-05-22 20:09 UTC, onuralpszr commented
@LinasKo I think this should fix the problem

2024-05-22 20:18 UTC, LinasKo commented
I'll review it, but I don't yet understand how this would fix the problem.

Give me a few minutes :wink:

2024-05-22 20:43 UTC, LinasKo approved these changes

2024-05-22 22:37 UTC, merged

2024-05-24 12:00 UTC, SkalskiP commented
Hi @onuralpszr and @LinasKo does any of you have Colab testing this change? :)

2024-05-24 12:01 UTC, onuralpszr commented
> Hi @onuralpszr and @LinasKo does any of you have Colab testing this change? :) 

I did share in issue and can share old one from issue link as well

2024-05-24 12:05 UTC, onuralpszr commented
@SkalskiP  my test is in here, I swap model and change video while I was testing, I can extend bit more

https://github.com/roboflow/supervision/issues/1219#issuecomment-2125379836

Other collab link : https://github.com/roboflow/supervision/pull/1222#discussion_r1610540398

2024-05-24 12:10 UTC, SkalskiP commented
Thanks @onuralpszr 🙏🏻