Feat/keypoints from mediapipe
roboflow/supervision pull request #1232
Opened 2024-05-27 16:22 UTC by David-rn

# Description

According to issue #1174, this PR extends the usage of KeyPoints class to add `from_mediapipe` connector. 

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [X] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

The following [Google Colab](https://colab.research.google.com/drive/1XN5yuqNDtS8Rakfh3q_Qxq_oo-WGfR0A?usp=sharing) describes the process used for testing this new feature. It allows to upload a picture to test it. (This Colab feature only worked in Chrome for me)

## Any specific deployment considerations

- This connector needs an additional parameter `resolution` since the result from mediapipe only provides the normalized coordinates [0.0, 1.0]. I didn't find the equivalent of [VideoInfo](https://github.com/roboflow/supervision/blob/2723735b018cf6f8907d4c706b5f759ff641a53d/supervision/utils/video.py#L15) for images, so the parameter accepts a Tuple of ints. 

- Another consideration is that mediapipe only outputs the prediction of [the most prominent person](https://github.com/google-ai-edge/mediapipe/blob/master/docs/solutions/pose.md) in the image. So, even if there is several people in the image, the output will be only the keypoints from one person. The implementation has taken this into account.

## Docs

-   [ ] Docs updated? What were the changes:

2024-05-27 16:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/roboflow/supervision?pullRequest=1232) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/roboflow/supervision?pullRequest=1232) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/roboflow/supervision?pullRequest=1232) it.</sub>

2024-05-27 19:15 UTC, SkalskiP commented
Hi, @David-rn 👋🏻 Thanks a lot for submitting your PR. @LinasKo, could you take a look?

2024-05-31 09:46 UTC, LinasKo requested changes
Overall, this is a very neat addition to our codebase. Easy to test, immediately visible benefit, neatly coded-up.

I left a few smaller changes, and I'd like to ask for some larger ones:

1. I'd like to verify that using this inside a `PoseLandmarker` context block works. If you follow the [guide](https://ai.google.dev/edge/mediapipe/solutions/vision/pose_landmarker/python) you'll see `PoseLandmarkerOptions` being created and then `with PoseLandmarker.create_from_options(options) as landmarker:` called. Inside, `Detections.from_mediapipe` should work.
2. Next, and that's something I've overlooked for the longest time didn't - MediaPipe does in fact support more than 1 person! To do it, you need to set the number of poses explicitly by passing `num_poses=N` to `PoseLandmarkerOptions`.

Would you mind making sure these work and adding the test to the Colab?
The docstring `from_mediapipe` doesn't need to mentioned these examples.

2024-05-31 09:46 UTC, LinasKo commented on supervision/keypoint/core.py
> +            resolution (Tuple[int, int]): image resolution (w, h) since mediapipe
I like the explanation for why it's needed :)

For our reference: `pose_world_landmarks` also normalized coordinates, but adjusted so origin is the point between the hips of the person.

2024-05-31 09:46 UTC, LinasKo commented on supervision/keypoint/core.py
> +            xy=np.array([prediction_xy], dtype=np.float32),
Let's make sure that when no predictions are returned, the empty array is still shaped `(0, -2)`.

For example:

```
if len(prediction_xy) == 0:
  return cls(
    xy=np.empty((1, 0, 2), dtype=np.float32),
    confidence=np.empty((1, 0,), dtype=np.float32)
)
```

2024-06-02 10:39 UTC, David-rn commented
Hi @LinasKo! Thanks for the suggestions!

> 1. I'd like to verify that using this inside a `PoseLandmarker` context block works. If you follow the [guide](https://ai.google.dev/edge/mediapipe/solutions/vision/pose_landmarker/python) you'll see `PoseLandmarkerOptions` being created and then `with PoseLandmarker.create_from_options(options) as landmarker:` called. Inside, `Detections.from_mediapipe` should work.

Regarding the first comment I discover that the use of `mp.solutions.pose.Pose` (the one I implemented) is a Legacy Solution as of March 1, 2023 as state [here](https://ai.google.dev/edge/mediapipe/solutions/guide). This confusion originated in the example Colab. The one you suggest in your comment is the new way to go. However, the result object is not the same as the legacy one. 

For this reason, should we provide support for both types or just focus on the new result? This is quite linked to the next comment.

> 2. Next, and that's something I've overlooked for the longest time didn't - MediaPipe does in fact support more than 1 person! To do it, you need to set the number of poses explicitly by passing `num_poses=N` to `PoseLandmarkerOptions`.

Regarding this second comment, indeed, it is now possible to obtain more than one pose, but only with the new implementation whose output object is of type [`PoseLandmarkerResult`](https://github.com/google-ai-edge/mediapipe/blob/2da0c56a5df3463af869dc365339225f0553d43b/mediapipe/tasks/python/vision/pose_landmarker.py#L57). This object holds a list of poses whereas the legacy one holds a different structure.

2024-06-02 10:51 UTC, LinasKo commented
1. How hard would it be to support both? If it's tricky to reason about or the code involved is complicated, let's stick to the new version. Even a few years back, I was already using the newer API, I believe.
2. Aye, let's add the newer one for sure in that case.

2024-06-02 15:56 UTC, David-rn commented
I think it wasn't that hard, but let me know if it is a nice solution:

I parsed the legacy result into a list (same as the new one) so the loop to fill the new KeyPoints object can remain the same for both results. I also updated the [Google Colab](https://colab.research.google.com/drive/1XN5yuqNDtS8Rakfh3q_Qxq_oo-WGfR0A?usp=sharing) to make easier the checking process.

2024-06-06 16:34 UTC, LinasKo commented
Hi @David-rn,

Apologies for the delay! Good to hear it supports both cases - I'm prioritizing to review this next week.

2024-06-11 11:03 UTC, LinasKo commented
Tidied up a few small aspects of this:
1. `(` instead of `[` making `mypy` happy
2. Removed legacy example. With our current plans to also add support for mediapipe face, this would bloat the docs.
3. Brought up to speed with `develop`.
4. Added inline suggestion to download model task. Initially intended to add a URL outside the code block, but it doesn't render nicely.
5. Tested on a local webcam.

<details>
  <summary>Code</summary>
  
  ```python
  import mediapipe as mp  # noqa
  import cv2
  import numpy as np
  import supervision as sv
  
  
  BaseOptions = mp.tasks.BaseOptions
  PoseLandmarker = mp.tasks.vision.PoseLandmarker
  PoseLandmarkerOptions = mp.tasks.vision.PoseLandmarkerOptions
  VisionRunningMode = mp.tasks.vision.RunningMode
  
  options = PoseLandmarkerOptions(
      base_options=BaseOptions(model_asset_path="pose_landmarker_lite.task"),
      running_mode=VisionRunningMode.IMAGE,
      num_poses=4,
  )
  
  cap = cv2.VideoCapture(0)
  
  
  with PoseLandmarker.create_from_options(options) as landmarker:
      # pose_landmarker_result = landmarker.detect(mp_image)
      while cap.isOpened():
          ret, frame = cap.read()
          if not ret:
              break
          mp_image = mp.Image(
              image_format=mp.ImageFormat.SRGB,
              data=cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
          )
  
          pose_landmarker_result = landmarker.detect(mp_image)
  
          image_hight, image_width, _ = frame.shape
          keypoints = sv.KeyPoints.from_mediapipe(pose_landmarker_result, (image_width, image_hight))
  
          edge_annotator = sv.EdgeAnnotator(color=sv.Color.GREEN, thickness=2)
          annotated_image = edge_annotator.annotate(
              scene=frame.copy(),
              key_points=keypoints,
          )
  
          cv2.imshow("image", annotated_image)
          if cv2.waitKey(1) & 0xFF == ord('q'):
              break
          
  cap.release()

  ```
</details>

I like how this looks. @SkalskiP, up for giving the code a quick glance?

2024-06-11 11:03 UTC, LinasKo approved these changes

2024-06-13 18:09 UTC, merged