Patch RichLabelAnnotator, fix others
roboflow/supervision pull request #1277
Opened 2024-06-12 12:15 UTC by LinasKo

# Description

Please include a summary of the change and which issue is fixed or implemented. Please also include relevant motivation and context (e.g. links, docs, tickets etc.).

List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

YOUR_ANSWER

## Any specific deployment considerations

For example, documentation changes, usability, usage/costs, secrets, etc.

## Docs

-   [ ] Docs updated? What were the changes:

2024-06-13 19:02 UTC, SkalskiP commented
@LinasKo I see a lot of `copy to` and `copy` operations. Have you measured how those impact performance?

2024-06-13 19:02 UTC, SkalskiP requested changes

2024-06-13 19:20 UTC, LinasKo commented
No. I'll do that, will let you know the results.

Realistically, it should be equivalent to frame.copy().

2024-06-18 19:25 UTC, LinasKo commented
1. Renamed to `ensure_cv2_image_...` and `ensure_pil_image_...`. I've seen this before, and we're not necessarily doing a conversion.
2. Removed a few copy operations. I finally understand why `cv2` has the destination parameter in methods like `addWeighted`, despite returning an image :)

The Colab now has tests in the end, comparing the performance on a 10,000x10,000 size empty image.
Results should show performance dips if any copying is expensive.

With the latest version, performance is equivalent or slightly better than in base supervision.

2024-06-19 07:45 UTC, LinasKo commented
Hey @onuralpszr ,

Given you've worked on it before, would you mind reviewing these changes too? There's a colab that shows how it works, only requiring that you upload the font file.

2024-06-19 08:37 UTC, onuralpszr commented
@LinasKo start reviewing

2024-07-03 11:38 UTC, SkalskiP approved these changes

2024-07-03 11:39 UTC, merged