COCO Detection Dataset Import/Export support
roboflow/supervision pull request #150
Opened 2023-06-25 11:56 UTC by hardikdava

# Description

- Added a support for `COCO` detection dataset import and export
- Added a support for reading and writing `json` files
- Related issue #141 

## Type of change

-   [x] New feature (non-breaking change which adds functionality)
-   [x] This change requires a documentation update

## How has this change been tested?

- Tested locally with dataset coco128 (downloaded from roboflow)
- Import using `supervision.DetectionDataset`
- Visualized using `supervision.BoxAnnotator`
- Saved dataset using `supervision.DetectionDataset`

## Docs

-   [x] Docs updated?

2023-06-26 08:47 UTC, yclicc commented
Is this supposed to support segmentation masks? It doesn't seem to be doing that for me, it only exports the bounding boxes.

2023-06-26 09:03 UTC, hardikdava commented
@yclicc Not yet. But it will be supported in near future. Currently, it is supporting only object detection format.

2023-06-26 10:45 UTC, SkalskiP commented
Hi @hardikdava 👋🏻 ! I was AFK at the CVPR conference last week. I'll do a code review today.

2023-06-26 11:10 UTC, hardikdava commented
@SkalskiP I also added support for instance segmentation masks loading. I tested locally. Please also test with coco segmentation dataset.

2023-06-26 11:16 UTC, hardikdava commented
> Is this supposed to support segmentation masks? It doesn't seem to be doing that for me, it only exports the bounding boxes.

@yclicc You can try now. It should be working.

2023-06-26 11:54 UTC, yclicc commented
@hardikdava that throws an error with my data on line 84 of dataset/formats/coco.py because "_polygons" is a dict. COCO format allows for segmentations either as a list of polygons or as a run length encoding (which is what I've got).

![image](https://github.com/roboflow/supervision/assets/9809447/ac52eae8-7061-44d8-9bb8-3bd3582bdc42)

2023-06-26 11:59 UTC, hardikdava commented
@yclicc , have you used latest code? please share your dataset if possible? I tried using segmentation dataset from roboflow.

2023-06-26 12:03 UTC, yclicc commented
This is latest code, but your code is expecting a list of polygons (which is a possible segmentation format for COCO, just not the only option). See https://opencv.org/blog/2021/10/12/introduction-to-the-coco-dataset/ for details and examples of both possible types of mask format.

2023-06-26 12:06 UTC, yclicc commented
I can't share my dataset, but I'm generating it with CVAT's mask annotation mode, as opposed to the polygon creator. So perhaps unsurprisingly, it has exported a COCO format with Run Length Encoding instead of a list of polygons.

2023-06-26 12:08 UTC, hardikdava commented
@yclicc this PR only supports for polygons. But I can take a look and check for possibility to extend the functionality.

2023-06-26 12:21 UTC, yclicc commented
I'll see if I can come up with a fix and then put in a pull request on your repo.

2023-06-26 16:49 UTC, SkalskiP commented
@hardikdava could you also run those two commands below in the root of your fork directory? This will ensure your new code is formatted constantly with rest of `supervision`.

```
black supervision
isort --profile black supervision/
```

2023-06-26 16:59 UTC, SkalskiP requested changes

2023-06-26 16:59 UTC, SkalskiP commented on supervision/dataset/formats/coco.py
> +        object: detections
Let's throw out this comment. It is redundant we see the type.

2023-06-26 16:59 UTC, SkalskiP commented on supervision/utils/file.py
> +def save_json_file(data: dict, file_path: str, indent=3):
Let's add type to `indent` argument. And add the return type `None`.

2023-06-26 16:59 UTC, SkalskiP commented on supervision/utils/file.py
> +class NpEncoder(json.JSONEncoder):
Could we rename it to `NpEncoder`? I prefer full names whenever possible.

2023-06-26 17:14 UTC, SkalskiP requested changes

2023-06-26 17:31 UTC, SkalskiP requested changes

2023-06-26 17:31 UTC, SkalskiP commented on supervision/dataset/core.py
> +            ...     annotations_directory_path=f"{dataset.location}/train/annotations.json",
Incorrect argument name in docs -`annotations_directory_path`. Inconsistent with method argument name -`annotations_path`.

2023-06-26 17:33 UTC, SkalskiP requested changes

2023-06-26 17:33 UTC, SkalskiP commented on supervision/dataset/core.py
> +            ...     annotations_directory_path=f"{dataset.location}/train/annotations.json",
Also Roboflow use a bit different naming convention so it is not `annotations.json` but `_annotations.coco.json`.

2023-06-26 17:48 UTC, hardikdava commented on supervision/dataset/formats/coco.py
> +    image_id = 0
@SkalskiP This implementation is done without pycocotools and I found `image_id` and `label_id` starting with `0` from roboflow dataset.

2023-06-26 17:58 UTC, hardikdava commented on supervision/dataset/formats/coco.py
> +def save_coco_annotations(
@SkalskiP I am breaking long method into shorter. Give me some time, please.

2023-06-26 18:02 UTC, SkalskiP commented on supervision/dataset/formats/coco.py
> +    image_id = 0
> I found `image_id` and `label_id` starting with `0` from roboflow dataset.

If so then that's good enough due diligence for me.

2023-06-26 18:06 UTC, hardikdava commented
@SkalskiP I have committed the changes you requested. Also ran two commands with `black` and `isort`. Please review it.

2023-06-26 18:26 UTC, SkalskiP requested changes

2023-06-26 18:26 UTC, SkalskiP commented on supervision/dataset/formats/coco.py
> +def _extract_class_names(annotation_data: dict) -> List[str]:
I noticed a bug in this method. It does not work with the hierarchy of classes. Could you take a look at this example?

```json
[
    {
        "id": 0,
        "name": "fashion-assistant",
        "supercategory": "none"
    },
    {
        "id": 1,
        "name": "baseball cap",
        "supercategory": "fashion-assistant"
    },
    {
        "id": 2,
        "name": "hoodie",
        "supercategory": "fashion-assistant"
    },
    {
        "id": 3,
        "name": "jacket",
        "supercategory": "fashion-assistant"
    },
    {
        "id": 4,
        "name": "pants",
        "supercategory": "fashion-assistant"
    },
    {
        "id": 5,
        "name": "shirt",
        "supercategory": "fashion-assistant"
    },
    {
        "id": 6,
        "name": "shorts",
        "supercategory": "fashion-assistant"
    },
    {
        "id": 7,
        "name": "sneaker",
        "supercategory": "fashion-assistant"
    },
    {
        "id": 8,
        "name": "sunglasses",
        "supercategory": "fashion-assistant"
    },
    {
        "id": 9,
        "name": "sweatshirt",
        "supercategory": "fashion-assistant"
    },
    {
        "id": 10,
        "name": "t-shirt",
        "supercategory": "fashion-assistant"
    }
]
```

Here `fashion-assistant` is a top category - parent to other categories. It should be discarded during loading. So it should be loaded as:

```
[
    'baseball cap',
    'hoodie',
    'jacket',
    'pants',
    'shirt',
    'shorts',
    'sneaker',
    'sunglasses',
    'sweatshirt',
    't-shirt'
]
```

Also, I'm not 100 sure if this implementation guarantee loading class names in the order of class ids.

2023-06-26 18:26 UTC, SkalskiP commented on supervision/dataset/formats/coco.py
> +def _extract_class_names(annotation_data: dict) -> List[str]:
I would even use that example as a case for the unit test.

2023-06-26 18:26 UTC, SkalskiP commented on supervision/dataset/formats/coco.py
> +        image = cv2.imread(str(image_path))
Just tested dataset loading and noticed that images were not loaded correctly.

Here is my code:

```python
import roboflow
from roboflow import Roboflow

roboflow.login()

rf = Roboflow()
project = rf.workspace("roboflow-jvuqo").project("fashion-assistant-segmentation")
dataset = project.version(5).download("coco")

import supervision as sv

ds = sv.DetectionDataset.from_coco(
     images_directory_path=f"{dataset.location}/train/images",
     annotations_path=f"{dataset.location}/train/_annotations.coco.json",
)
```

And images got loaded as:

```
...
'photo_2023-05-30-17-34-54_jpeg.rf.593fa7603782b4679c624d5c1f63a508.jpg': None,
 'photo_2023-05-29-12-28-55_jpeg_jpg.rf.5a577cabb1aa09018e06fe01640bbb03.jpg': None,
 'photo_2023-05-29-12-29-08_jpeg_jpg.rf.5bd8bfb57cd46e45f2fd8ff9bfa34de1.jpg': None,
 'photo_2023-05-29-14-10-23_jpeg_jpg.rf.5d4449e52e9dcdf25ef1f5b3f1c1b62c.jpg': None,
 'photo_2023-05-30-17-35-05-1-_jpeg.rf.5c217edf22eab45f1761f3972453d469.jpg': None,
 'photo_2023-05-30-17-34-57_jpeg.rf.5959091a468b991b5794778f093c881a.jpg': None,
 'photo_2023-05-29-12-29-12_jpeg_jpg.rf.5b0744781d8f14023a55a9edadfc23b1.jpg': None,
...
```

2023-06-26 18:29 UTC, SkalskiP commented
@hardikdava I did some tests and noticed two critical bugs. I marked them in the code. You can also use this Google Colab as reference: https://colab.research.google.com/drive/1spwwYyYO-LN3RDzp5s8whG1_7JzROm-m?usp=sharing

2023-06-26 18:30 UTC, SkalskiP commented
@hardikdava 

> I would like to work on new features. I know unittests are important but I am not fan of implementing them ;)

No worries I can take care of that. For now, let's make sure simple tests in Google Colab work. And when we will be done with that. I'll make unittests ;)

2023-06-26 18:37 UTC, SkalskiP commented
@hardikdava I've done that already :) Also, do I have the right to commit to your fork? I could start to work on unit tests on your branch.

2023-06-26 23:54 UTC, SkalskiP commented on supervision/dataset/formats/coco.py
> +def _extract_class_names(annotation_data: dict) -> List[str]:
@hardikdava I solved that problem with https://github.com/roboflow/supervision/pull/150/commits/540efc80ce2cfcd37539d35a621575db1f536764

2023-06-27 01:07 UTC, SkalskiP commented
Hi @hardikdava 👋🏻 ! I spend a few hours today writing unit tests and code re-factorication. I'm not done yet, but I hope I'll finish tomorrow. So far so good.

2023-06-27 06:13 UTC, hardikdava commented
Hi @SkalskiP 👋🏻 , I checked your commits. I have to adopt coding style to supervision format. Let me know if I can help you in anyway in progress. I would like to keep continue contributions.

2023-06-27 09:59 UTC, SkalskiP commented
> I have to adopt coding style to supervision format.

No worries :) I try to keep API and style consistent.

> Let me know if I can help you in anyway in progress. I would like to keep continue contributions.

For now, my work comes down primarily to writing unit tests and cleaning up here. As you try to stay away from testing, I think I can take it from here, but we can think about the next task for you.

2023-06-27 11:57 UTC, SkalskiP approved these changes

2023-06-27 11:57 UTC, SkalskiP commented
Hi @hardikdava 👋🏻 ! We are ready for merge ;)

2023-06-27 11:58 UTC, merged

2023-06-27 13:12 UTC, hardikdava commented
Hi @SkalskiP 👋🏻, thanks for merging my contribution. I am glad to see my contribution in community. Always happy to help! how should we discuss about new feature in github or else?

2023-06-27 13:41 UTC, SkalskiP commented
@hardikdava 🔥 

- I'm still working on the description of the API for: https://github.com/roboflow/supervision/discussions/153. I want to do it right so it will probably take me a while to come up with something I'd be happy with.
- Would you like to take care of: https://github.com/roboflow/supervision/issues/155?

2023-06-28 10:12 UTC, yclicc commented
I've found a problem with this code, in that the image_annotation["category_id"] might be indexed from 1 instead of from zero, or may even skip numbers (not sure if that is valid COCO, but it should be coped with properly). However, coco_categories_to_classes returns the class names as an (obviously zero indexed) list with no skips, but then coco_annotations_to_detections sets the class_ids to simply the image_annotation["category_id"] even though this may not be zero indexed.

2023-06-28 12:19 UTC, SkalskiP commented
Hi @yclicc, I noticed that problem while reviewing one of the current PRs. The fix should be in `main` now. Could you try using it once again?

2023-06-28 12:26 UTC, yclicc commented
Yep, that's fixed it. Thanks!

2023-06-28 12:50 UTC, SkalskiP commented
@yclicc awesome! We will probably release those changes today or tomorrow.

2023-06-28 13:44 UTC, yclicc commented
Ah, no I'm afraid this is still present. Suggest modifying coco_categories_to_classes to make it also return a lookup table from category["id"] to index in the new category list.

2023-06-28 14:13 UTC, SkalskiP commented
I just tested it. It works for me. Making it a lookup table would require changing every other format we support. Can you give me any example of a dataset it doesn't work for?

2023-06-28 14:22 UTC, yclicc commented
Any COCO dataset where the numbering of the ids of the categories doesn't start at 0 and/or skips a number.

E.g. ```"categories": [{"id":1, "name":"Albatross", "supercategory": ""}, {"id": 3,"name":"Walrus", "supercategory":""}]```
That will then return a dataset.yaml of the form
```
names:
- Albatross
- Walrus
nc: 2
```
but the indices of each row of the YOLO dataset will be 1 and 3 instead of 0 and 1. By a lookup table, you don't need to modify anything except the COCO code. Have coco_categories_to_classes return a lookup table, then have coco_annotations_to_detections accept that lookup table and then when the class_ids variable is set have it lookup in that lookup table for each `image_annotation["category_id"]`. The only downside is that converting from COCO to itself will lose information by changing the IDs in the outputted COCO. But I'd say that's a price worth paying to have the result work properly with YOLO.

2023-06-28 14:32 UTC, SkalskiP commented
So the ids of your input dataset are not ordered from `0` to `n-1` where `n` is the number of categories? I see how it breaks. 

In that case, we have two options:
- Remapping ids during COCO loading (I would prepare that)
- Storing classes as dictionary not a list

2023-06-28 14:47 UTC, SkalskiP commented
@yclicc Yeah this is something that we need to take into consideration :/

2023-06-29 09:51 UTC, SkalskiP commented
@hardikdava could you take a look at the problem @yclicc described?

2023-06-29 10:15 UTC, hardikdava commented
@SkalskiP sure. I will take a look at it and try to fix it.

2023-06-29 12:28 UTC, SkalskiP commented
@hardikdava awesome!

2023-06-29 14:47 UTC, hardikdava commented
@SkalskiP and @yclicc some of the things I found about coco dataset.


**Issue: Category map ids assignment**
- COCO dataset category map ids starting from `1` not `0`. Source:  [src1](https://www.v7labs.com/blog/coco-dataset-guide) [src2](https://www.immersivelimit.com/tutorials/create-coco-annotations-from-scratch) [src3](https://opencv.org/blog/2021/10/12/introduction-to-the-coco-dataset/)
- But coco dataset downloaded from Robfolow has category map ids starting from `0`.
- Even though starting ids from `0` does not create an issue. Tested with pycocotools(python API to work with coco dataset).
- We can make it something like ids will start from `1` for only coco dataset.

**Issue: Segmentation polygon type**
- I only found the below suggested format by [opencv university](https://opencv.org/blog/2021/10/12/introduction-to-the-coco-dataset/) and @yclicc 
```
“annotations”: [{
    ”segmentation”:
    {	
        “counts”: [34, 55, 10, 71]
        “size”: [240, 480]
    },
    “area”: 600.4,
    “iscrowd”: 1,
    “Image_id:” 122214,
    “bbox”: [473.05, 395.45, 38.65, 28.92],
    “category_id”: 15,
    “id”: 934
}
```
- I personally download instance segmentation label from CVAT and it does not have above mentioned format.
- I would suggest let the segmentation as polygons and later if we receive some more issue from other users then we will plan to improve it. 

Let me know your views soon.

2023-06-29 14:53 UTC, yclicc commented
**Category map ids assignment**
The thing is, once it is loaded as a detection we want it to be agnostic to the fact that came from COCO format. So you would want to make it zero indexed so that when it is then written to YOLO (the most common usecase for the Supervision library I would think?) it works properly and plays nicely with the YOLO models. If indeed it is the _convention_ to start at 1 for COCO then the exporter that goes back to COCO could of course do that.

**Segmentation polygon type**
It remains the case that the RLE format is part of the COCO spec, though, so you may assume that people will try to load such data in. As it is now, it throws an unhandled exception when this happens. Might it be worth at least doing a try catch and raising a NotImplementedError if segmentation is a dict instead of a numpy array?

2023-06-29 15:23 UTC, hardikdava commented
@yclicc my thoughts,

**Segmentation polygon type**
I can add something like if the segmentation annotation datatype is `dict` then it will raise `NotImplementedError`. This can easily be done.

**Category map ids assignment**
- `supervision` is not bounded by `yolo`. So it has to be work with `yolo` or any other format.
- The idea of offset will be included while writing the coco dataset. But currently, `supervision` does not have any information whether the original dataset is loaded from `coco` or `yolo` so think of following situations:
- situation-1: dataset is loaded from `coco` and saving in `coco` format then offset of `1in class_id` is not needed. Because `class_id` is already starting from `1`
- situation-2: dataset is loaded from other than `coco` format and saving in `coco` format then offset of `1 in class_id` is needed as `coco` `class_ids` are starting from `1`.

2023-06-29 18:51 UTC, SkalskiP commented
Hi @hardikdava and @yclicc 👋🏻 How about we just remap class ids when we load COCO annotations?

2023-06-30 12:50 UTC, hardikdava commented
@yclicc @SkalskiP Found the solution. We should offset the `coco-category_id` by `-1` when we load the coco dataset. So every `class ids` are starting from `0` regardless of dataset. We can offset `class id` by `+1` while we are storing dataset only for `coco` format. This will fix the issue of storing the dataset. I do not see any issue for this.

2023-06-30 13:57 UTC, hardikdava commented
@yclicc can you try with #169 ? Let me know how it goes.

2023-07-04 15:38 UTC, SkalskiP commented
@yclicc I created a fix for this issue https://github.com/roboflow/supervision/pull/176. Could you take a look and try to see if it works?

2023-07-05 07:02 UTC, yclicc commented
Seems good to me, though it still fails as my dataset contains RLEs rather than polygons.

2023-07-05 07:13 UTC, yclicc commented
Yep, all seems to work fine when I add my RLE code back in (which sadly I can't share). Thanks!

2023-07-05 09:26 UTC, SkalskiP commented
> Yep, all seems to work fine when I add my RLE code back in (which sadly I can't share). Thanks! 

@yclicc We will add `RLE` support in feature releases 💯 Thanks for testing. 

@hardikdava looks like we will move forward with https://github.com/roboflow/supervision/pull/176.