feat: 🚀 initial keypoint support for transformers added
roboflow/supervision pull request #1553
Opened 2024-09-27 15:44 UTC by onuralpszr

# Description

Recent release of transformers introduce keypoint support and initial support for keypoint added. 

## Type of change

-   [X] New feature (non-breaking change which adds functionality)
-   [X] This change requires a documentation update

## Docs

-   [X] Docs updated? What were the changes:

2024-09-27 16:04 UTC, onuralpszr commented
@merveenoyan 👋  hello I notice current latest and dev doesn't have "post_process_keypoint_detection" function and I was able to run via only this pull request branch "https://github.com/huggingface/transformers/pull/33200" Today I read about "https://huggingface.co/docs/transformers/tasks/keypoint_detection" you posted in social and I was unable run keypoint only I was able to do via using install this repo/branch

`!pip install git+https://github.com/sbucaille/transformers@superpoint_fix -q`

Error output

```
    outputs = processor.post_process_keypoint_detection(outputs, image_sizes)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SuperPointImageProcessor' object has no attribute 'post_process_keypoint_detection'
```

Here is my initial collab link for working version 

https://colab.research.google.com/drive/1gxpE9iDR7gXl2VwwScB5W8Yw-e_xUo3i?usp=sharing

2024-10-01 06:54 UTC, onuralpszr commented
@LinasKo missing function basically converting normalize values to w,h values to position correctly should I finish based on that in current release and finish the PR ?

2024-10-01 08:09 UTC, LinasKo commented
@onuralpszr, I need more details.

1. Missing function where? Our repo or theirs?
2. "should I finish based on that in current release and finish the PR ?" - Based on what? Based on the function being missing? I'd like more clarity here 😉

2024-10-01 08:31 UTC, onuralpszr commented
> @onuralpszr, I need more details.
> 
> 1. Missing function where? Our repo or theirs?
> 2. "should I finish based on that in current release and finish the PR ?" - Based on what? Based on the function being missing? I'd like more clarity here 😉


Sorry, I was little bit hasty I guess and for answering your questions 

1 - Missing function is theirs and it is post process function for converting normalize xy values to pixel based on xy values (post_process_keypoint_detection is missing)
2 - Currently latest version of transfomers has SuperPointImageProcessor but, doesn't have SuperPointImageProcessor.post_process_keypoint_detection() so I will finish PR based on latest version of transformers to  and I will write the helper function to convert image size correction  or I had to assume it does use function and leave as it is. You can check the PR link I posted above to see it.

2024-10-16 01:44 UTC, onuralpszr commented
@LinasKo I see approve so I am going to move forward  based on this PR  ("[huggingface/transformers#33200](https://github.com/huggingface/transformers/pull/33200)" ) I am going to finish this PR

2024-10-17 08:12 UTC, LinasKo requested changes
I added a few small comments. Let's wait until they merge the change, test it in a Colab, and then merge it!

2024-10-17 08:12 UTC, LinasKo commented on supervision/keypoint/core.py
> +            xy=np.array(keypoints_list),
In `Detections` we always set the dtype here just in case.

Let's do the same.

2024-10-17 08:12 UTC, LinasKo commented on supervision/keypoint/core.py
> +            confidence=np.array(scores_list),
Let's add a dtype to confidence as well.

2024-10-17 08:12 UTC, LinasKo commented on supervision/keypoint/core.py
> +            class_id=None,
Do we need to explicitly set it to `None`?

2024-11-02 07:29 UTC, LinasKo commented
Hey @onuralpszr ,

How's this one going? Is it ready for review, or is there some work left to do?

2024-11-02 08:40 UTC, onuralpszr commented
> Hey @onuralpszr ,
> 
> How's this one going? Is it ready for review, or is there some work left to do?

I have small problem when I detect multiple images at once keypoint list doesn't come in same sizes. Point lists are different

2025-02-17 22:10 UTC, closed without merging