Feat: Added detection metadata
roboflow/supervision pull request #1589
Opened 2024-10-10 20:54 UTC by souhhmm

# Description

As per,
- #1585 

implemented detection metadata and updated related methods. Please let me know if anything needs to be fixed/changed.

## Type of change

-   [x] New feature (non-breaking change which adds functionality)
-   [x] This change requires a documentation update (probably)

## How has this change been tested, please provide a testcase or example of how you tested the change?

Here's the [link to the colab](https://colab.research.google.com/drive/1HaK7SUhFTsHgsi4QUcf6FTSe70SLstGj?usp=sharing) that tests the implemented code.

2024-10-13 08:20 UTC, souhhmm commented
Hey @LinasKo, it says the 'Welcome Workflow' check has failed. Is this the reason the review has been halted?

2024-10-13 08:22 UTC, LinasKo commented
It's a mistake on our part. Don't worry about that one :wink:

2024-10-15 08:21 UTC, souhhmm commented
Hey @LinasKo, any updates/feedback?

2024-10-15 08:23 UTC, LinasKo commented
On it, on it. This one will take time, likely the whole week. It can have consequences across the repo, so I must be very careful.

2024-10-15 08:26 UTC, souhhmm commented
No worries, take your time.

2024-10-15 12:51 UTC, LinasKo requested changes

2024-10-15 12:51 UTC, LinasKo commented on supervision/detection/core.py
> +        )
This widens the description of what `empty` is allowed to be. Let's keep it as it was. It'll get simplified when we solve #943

2024-10-15 12:51 UTC, LinasKo commented on supervision/detection/core.py
>          validate_detections_fields(
In `Detections.empty()` you set the metadata to `metadata=metadata if metadata is not None else`. Let's add some validation, making sure it's a `dict`.

2024-10-15 12:51 UTC, LinasKo commented on supervision/detection/core.py
> +        )
I like the optional metadata argument for `empty`, but let's avoid checking for it here (similarly to how we avoided `data` check).

Suppose there is a model that returns values `{detection, X, Y}` when detections are successful and `{[], X}` when nothing is detected. This prevents the developers from using the metadata system if they ever want to add `Y`.

Ultimately, I'd like to simplify this to `len(self.xyxy) == 0`, but only after the next release, to have time for testing.

2024-10-15 12:51 UTC, LinasKo commented on supervision/detection/core.py
> +                self.metadata == other.metadata,
I suggest creating another function `is_metadata_equal` which checks that keys are equal. Then, for each value, if it's a numpy array, it checks with `np.array_equal` and then normal `==`.

In later PRs we could also call it recursively if it's a dict, but maybe let's not do that yet.

2024-10-15 12:51 UTC, LinasKo commented on supervision/detection/utils.py
> +def merge_metadata(metadata_list: List[Dict[str, Any]]) -> Dict[str, Any]:
Contrary to how leniently we treat `Detections.empty`, let's be more aggressive here.

Using similar logic to `__eq__`, let's make sure that for all non-empty metadata, all the keys and values are the same.

If it's different, let's raise an error.

2024-10-15 12:51 UTC, LinasKo commented on supervision/detection/utils.py
> +def merge_metadata(metadata_list: List[Dict[str, Any]]) -> Dict[str, Any]:
My goal is to tighten new data structures, while keeping old ones, with known issues, more lenient.

2024-10-15 12:54 UTC, LinasKo commented
I've made some comments. I like your changes so far!

It shows you've thought through the problem, in places like introducing of optional variable in `empty`, while avoiding the pitfall of incorrectly defaulting to `{}`.

2024-10-16 06:23 UTC, souhhmm commented
Hey @LinasKo, I have made the required changes. Please let me know about further changes/fixes. Thanks :)

2024-10-17 08:05 UTC, LinasKo commented
That looks good.

The next request for every contribution is to create a Colab to test the changes. This would involve creating Detections with and without metadata showing how it works & testing with multiple values. It's slightly easier than unit testing, and is also a doc we refer to later on, when we wish to test for regressions.

Got any time for that, @souhhmm? There's a [Starter Template](https://colab.research.google.com/drive/1rin7WrS-UvVIe-_Gfxmu-yVslGphOq89#scrollTo=pjmCrNre2g58) you may use 😉

2024-10-17 08:55 UTC, souhhmm commented
I had linked a colab in the og PR, [linking once again](https://colab.research.google.com/drive/1HaK7SUhFTsHgsi4QUcf6FTSe70SLstGj?usp=sharing). But now that I have changed some code, I'll re-run it.

2024-10-18 10:21 UTC, LinasKo commented
Hi @souhhmm 👋 

My apologies, I missed your Colab. That is indeed an amazing set of tests.
I'll take over from this point - there's a few checks I need to do before I merge this.

2024-10-18 10:47 UTC, souhhmm commented
No worries, thanks to you too for your great feedback :)

2024-11-04 11:18 UTC, LinasKo commented
Thank you for a fantastic contribution @souhhmm!

Most take me hours to verify, but with your test suite and thoughtful changes, I barely had to do anything. Expect to see it in the next supervision release at the end of this week!

2024-11-04 11:19 UTC, LinasKo approved these changes

2024-11-04 11:19 UTC, merged