Allow "tiff" and more extensions in `DetectionDataset.from_yolo` function
roboflow/supervision pull request #1636
Opened 2024-10-31 14:03 UTC by patel-zeel

# Description

Addresses #1554 as discussed with @LinasKo.

## Highlights
- [x] Allows any image extension in `DetectionDataset.from_yolo`.
Tested extensions (listed on [Ultralytics predict page](https://docs.ultralytics.com/modes/predict/#images)):
    - [x] bmp
    - [x] jpg
    - [x] mpo
    - [x] png
    - [x] tif
    - [x] webp
    - [ ] pfm - `Pillow` could not read `pfm` images, `cv2` is able to read them. I saw [here](https://github.com/ultralytics/ultralytics/blob/f4e7756bff5c1b0c246afb491f42e9f9de84dc84/ultralytics/models/yolo/classify/predict.py#L46) that even Ultralytics uses `Pillow` to read images. In that case, I am not sure if Ultralytics can "really" support `pfm` format, as their documentation suggests.
    - [x] dng
- [x] Image must be of "RGB" type, raise `ValueError` otherwise.

List any dependencies that are required for this change.
* `Pillow`

## Type of change

Please delete options that are not relevant.

-   [x] New feature (non-breaking change which adds functionality)

## How has this change been tested, please provide a testcase or example of how you tested the change?

The changes are tested with [this colab notebook](https://colab.research.google.com/drive/17oe0lxQXHCABllLynG93cVMVpuwww2bb?usp=sharing).

### Test Case

100 images of each extension were generated along with their corresponding dummy labels and dummy `data.yml`. Test run checks if the function works for a particular extension and computes time taken to load the dataset.

Time taken (in seconds) to run the test case. Columns 0,1,2,3,4 are seed numbers. `-1.11` value indicates that `supervision` doesn't support that extension yet.
* Result for `supervision` version `0.24.0`, which uses `cv2` to check the shape of images.

|      |     0 |     1 |     2 |     3 |     4 |   Mean |   Std |
|:-----|------:|------:|------:|------:|------:|-------:|------:|
| bmp  | -1.11 | -1.11 | -1.11 | -1.11 | -1.11 |  -1.11 |  0.00    |
| jpg  |  0.98 |  1.16 |  0.85 |  0.76 |  0.77 |   0.90  |  0.15 |
| mpo  | -1.11 | -1.11 | -1.11 | -1.11 | -1.11 |  -1.11 |  0.00    |
| png  |  0.58 |  0.56 |  0.42 |  0.4  |  0.41 |   0.48 |  0.08 |
| tif  | -1.11 | -1.11 | -1.11 | -1.11 | -1.11 |  -1.11 |  0.00  |
| webp | -1.11 | -1.11 | -1.11 | -1.11 | -1.11 |  -1.11 |  0.00    |
| dng  | -1.11 | -1.11 | -1.11 | -1.11 | -1.11 |  -1.11 |  0.00   |

* Result for this PR, which uses `Pillow` to check the shape and type (RGB or not) of images.

|      |    0 |    1 |    2 |    3 |    4 |   Mean |   Std |
|:-----|-----:|-----:|-----:|-----:|-----:|-------:|------:|
| bmp  | 0.04 | 0.02 | 0.02 | 0.02 | 0.03 |   0.03 |  0.01 |
| jpg  | 0.03 | 0.02 | 0.03 | 0.02 | 0.02 |   0.03 |  0.00    |
| mpo  | 0.04 | 0.04 | 0.06 | 0.04 | 0.04 |   0.04 |  0.01 |
| png  | 0.02 | 0.02 | 0.04 | 0.02 | 0.02 |   0.02 |  0.01 |
| tif  | 0.05 | 0.06 | 0.08 | 0.05 | 0.05 |   0.06 |  0.01 |
| webp | 0.10  | 0.11 | 0.11 | 0.09 | 0.11 |   0.10  |  0.00    |
| dng  | 0.06 | 0.06 | 0.05 | 0.06 | 0.06 |   0.06 |  0.00    |

## Docs

-   [ ] Docs updated? What were the changes: **Not changed, please suggest if we need changes in the docs**

2024-10-31 14:12 UTC, LinasKo commented
You never cease to surprise, @patel-zeel; such a thorough analysis! ⭐

Adding this to the back of my review backlog, but I already know it will be a delight.

2024-11-01 07:55 UTC, patel-zeel commented
Thank you for your kind words, @LinasKo. It's a pleasure to help improve a widely used library. Looking forward to your feedback!

2024-12-31 09:56 UTC, patel-zeel commented
@LinasKo a small correction. I recently found that Ultralytics uses [this function](https://github.com/ultralytics/ultralytics/blob/f932a611abf0ed0e359deecbb82fa8d361e23cfe/ultralytics/utils/patches.py#L15-L26) to read `pfm` and other image files during `yolo predict` call. It uses `cv2` and not `Pillow`. So, I was able to process `pfm` images with Ultralytics. However, the fact remains that Pillow does not support colored `pfm` images. [This PR](https://github.com/python-pillow/Pillow/pull/7696) added greyscale `pfm` support in Pillow and it points to [this issue](https://github.com/python-pillow/Pillow/issues/1888) for not supporting color images. [The issue](https://github.com/python-pillow/Pillow/issues/1888) is pinned on Pillow since May 2016 and thus, it seems the issue is not going to be resolved in near future. However, unless `pfm` format dominates some domains, we are not bottlenecked by it.

2025-01-08 09:15 UTC, SkalskiP requested changes

2025-01-08 09:15 UTC, SkalskiP commented on supervision/dataset/formats/yolo.py
> +        if image.mode != "RGB":
@patel-zeel looks like we can simplify the code here. There is no need for nested ifs.
```python
if image.mode not in ("RGB", "L"):
    raise ValueError(
        f"Images must be 'RGB' or 'grayscale', but {image_path} mode is '{image.mode}'."
    )
```

2025-01-08 09:15 UTC, SkalskiP commented on supervision/dataset/formats/yolo.py
> +                image = image.convert("RGB")
It seems to me that conversion to RGB is not necessary. The image is not used in the further part of the function.

2025-01-08 09:15 UTC, SkalskiP commented on supervision/dataset/formats/yolo.py
> +            directory=images_directory_path, extensions=["*"]
There is a small but important side-effect of this change. If there are other files than images in the directory, we will also try to load them. For example, macOS puts a `.DS_Store` file in the directory. @patel-zeel I suggest putting here a list of image extensions that you have tested.

2025-01-08 09:25 UTC, SkalskiP commented
@patel-zeel I apologize for making you wait so long for a review of this PR. I was on a long break at the turn of the year. I left some comments, please address them.

2025-01-08 09:29 UTC, patel-zeel commented on supervision/dataset/formats/yolo.py
> +                image = image.convert("RGB")
Right, that'd save us the time wasted in the conversion. I checked the other extreme as well. If we convert all images to RGB by default, that adds a bit of unnecessary overhead. So, this change will improve the speed further. Thank you for pointing it out, @SkalskiP.

2025-01-08 09:30 UTC, patel-zeel commented on supervision/dataset/formats/yolo.py
> +            directory=images_directory_path, extensions=["*"]
I agree. On it!

2025-01-08 09:34 UTC, patel-zeel commented
No worries, @SkalskiP, I hope you had a good time during the break. Thank you for the review! I have addressed the changes.

2025-01-08 10:37 UTC, SkalskiP commented
@patel-zeel one more small comment and we should be good to go

2025-01-08 10:58 UTC, patel-zeel commented on supervision/dataset/formats/yolo.py
> +            extensions=[
I kept them in a single line @SkalskiP. Pre-commit (I think ruff) forced them on separate lines. Do we want to override that?

2025-01-08 11:41 UTC, SkalskiP commented on supervision/dataset/formats/yolo.py
> +            extensions=[
eeeh that's what I thought so

2025-01-08 11:41 UTC, SkalskiP approved these changes

2025-01-08 11:42 UTC, merged

2025-01-09 03:51 UTC, patel-zeel commented
Thank you for the review and merge, @SkalskiP! 

I'd like to mention that this PR not only extends the support for more image extensions but also significantly speeds up the data loading with the `sv.DetectionDataset.from_yolo` function. The speed up is around 14x (or 1300%) as demonstrated in [this colab](https://colab.research.google.com/drive/1CiethT59rzFYZyXZI-nsHjZbjP0ZEI_q?usp=sharing).

2025-01-09 09:26 UTC, SkalskiP commented
Hi @patel-zeel 👋🏻 yes I know! in fact this is the main angle I plan to use when promoting this change.