🛠️ fix incorrect COCO class id loading
roboflow/supervision pull request #176
Opened 2023-07-04 15:34 UTC by SkalskiP

# Description

Draft of PR fixing issues mentioned https://github.com/roboflow/supervision/pull/150. It is an alternative to the https://github.com/roboflow/supervision/pull/169 solution.

2023-07-04 18:36 UTC, SkalskiP commented
Hi, @hardikdava 👋🏻 did you have a chance to test this?

2023-07-04 18:50 UTC, hardikdava commented
@SkalskiP Let me test and confirm your fix.

2023-07-04 19:02 UTC, hardikdava commented
@SkalskiP Test summary:

Situation-1: `from_coco()` -> `to_coco()`
Works fine if `image_id` and `labels_id` starts with `0`

Situation-2: `from_yolo()` -> `to_coco()`
`image_id` and `labels_id` starts with `0` after saving as coco format. But no mixed up in categories.

2023-07-04 22:48 UTC, SkalskiP commented
@hardikdava, as for case 2, do you think we would like `image_id` and `labels_id` to start from `1`?

2023-07-05 08:45 UTC, hardikdava commented
@SkalskiP Yes, based on my research and description from coco, opencv, etc it is their standard format to start `image-id` and `label-id` starting from `1`. Once this is fixed then we are good to go.

2023-07-05 09:32 UTC, hardikdava requested changes
Please make this small changes and we can close this.

2023-07-05 09:32 UTC, hardikdava commented on supervision/dataset/formats/coco.py
@SkalskiP Can you make following changes then we are done with coco format. 

file: coco.py line:202 and 203
``
    image_id = 1
    annotation_id = 1
``

2023-07-05 09:32 UTC, SkalskiP commented
@hardikdava, that should be easy. I'll update `.to_coco` logic before merging.

2023-07-05 09:35 UTC, SkalskiP commented
@hardikdava given the fact that @yclicc tested the code and it works as expected. (read more here https://github.com/roboflow/supervision/pull/150) I'll probably close https://github.com/roboflow/supervision/pull/169. Is it okey with you?

2023-07-05 09:35 UTC, hardikdava commented
@SkalskiP Yes, please mark it as completed.

2023-07-05 09:37 UTC, SkalskiP commented on supervision/dataset/formats/coco.py
done

2023-07-05 09:38 UTC, hardikdava approved these changes

2023-07-05 09:40 UTC, merged