Paddledet support
roboflow/supervision pull request #191
Opened 2023-07-13 17:48 UTC by hardikdava

# Description

This PR is in support for #187 

## Type of change

-   [x] New feature (non-breaking change which adds functionality)
-   [x] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

Find colab [here](https://drive.google.com/file/d/1R8mLUFsoflwTK4PSfnOXmKtw7Keu2zlX/edit?pli=1)

## Docs

-   [ ] Docs updated? What were the changes:

2023-07-20 17:52 UTC, SkalskiP commented
@hardikdava, do you want to ship it in this release?

2023-07-20 17:59 UTC, hardikdava commented
@SkalskiP yeah, we can include it.

2023-07-21 09:27 UTC, SkalskiP commented
@hardikdava, do you have some Colab I could use to test it?

2023-07-21 09:27 UTC, SkalskiP requested changes

2023-07-21 09:27 UTC, SkalskiP commented on supervision/detection/core.py
> +    def from_paddledet(cls, paddledet_result):
We will also need a docstring for this connector.

2023-07-21 09:41 UTC, hardikdava commented
> @hardikdava, do you have some Colab I could use to test it?

[Here](https://colab.research.google.com/drive/1R8mLUFsoflwTK4PSfnOXmKtw7Keu2zlX#scrollTo=5ESh2QrCbbGn) you go.

2023-07-21 09:44 UTC, SkalskiP commented
> Here

I don't have access :/

2023-07-21 09:45 UTC, hardikdava commented
> > Here
> 
> I don't have access :/

Check now please.

2023-07-21 10:17 UTC, SkalskiP commented
@hardikdava I'm unsure if I'm doing something wrong, but the Colab fails. I get an exception.

![Screenshot 2023-07-21 at 12 17 11](https://github.com/roboflow/supervision/assets/26109316/e8519535-1936-48a6-b2ab-24f091e39686)

2023-07-21 10:21 UTC, hardikdava commented
Yeah, I am also getting same error. But it was working fine :laughing:

2023-07-21 10:29 UTC, SkalskiP commented
@hardikdava would you have a bit of time to take a look at it?

2023-07-21 11:44 UTC, hardikdava commented
@SkalskiP  I tried various installation but I could not do it. Let's keep this on next release.

2023-07-21 12:00 UTC, SkalskiP commented
@hardikdava, no worries! 🙏🏻 I plan to close `0.12.0` release on Monday. I'm happy to move this one to `0.13.0` and have our full focus on things we can still close.

2023-07-22 09:58 UTC, hardikdava commented
hello @SkalskiP , I fixed the colab test. Please test it with update colab: https://colab.research.google.com/drive/1R8mLUFsoflwTK4PSfnOXmKtw7Keu2zlX?usp=sharing

2023-07-22 15:31 UTC, SkalskiP commented
@hardikdava I'm still trying to figure out what's going on, but I still doesn't work for me. 

![Screenshot 2023-07-22 at 17 30 34](https://github.com/roboflow/supervision/assets/26109316/9f6b3fdf-add0-4503-a0c0-e728f9e8d65a)

2023-07-22 17:27 UTC, onuralpszr commented
> @hardikdava I'm still trying to figure out what's going on, but I still doesn't work for me.
> 
> ![Screenshot 2023-07-22 at 17 30 34](https://user-images.githubusercontent.com/26109316/255337704-9f6b3fdf-add0-4503-a0c0-e728f9e8d65a.png)

Let me take tackle this a little bit I think I have an idea......

2023-07-22 17:28 UTC, hardikdava commented
@onuralpszr thanks. I like how we are helping each other with bugs and errors.

2023-07-22 17:32 UTC, onuralpszr commented
@hardikdava  @SkalskiP  hurray :)) 

![image](https://github.com/roboflow/supervision/assets/1688848/f3aab5a7-d4e6-46ec-9502-35ac0950cf0e)

2023-07-22 17:33 UTC, onuralpszr commented
Do this commands then re-import again

```bash
!wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
!sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
```

2023-07-25 10:49 UTC, SkalskiP commented
@hardikdava am I correct to assume we are ready to merge here?

2023-07-25 10:52 UTC, onuralpszr commented
> @hardikdava am I correct to assume we are ready to merge here? 

Also, Did you able to run with my fix ?

2023-07-26 11:06 UTC, hardikdava commented
> > @hardikdava am I correct to assume we are ready to merge here?
> 
> Also, Did you able to run with my fix ?

Thanks @onuralpszr. yeah, I was able to run it.

2023-07-28 12:55 UTC, SkalskiP approved these changes

2023-07-28 12:57 UTC, SkalskiP commented
Hi @hardikdava! 👋🏻 Just tested your Colab. Looks good. Merging! 🔥

2023-07-28 12:57 UTC, merged