Add support for loading segmentation datasets in Pascal VOC format
roboflow/supervision pull request #245
Opened 2023-07-26 08:25 UTC by kirilllzaitsev

# Description

Add possibility to load PASCAL VOC segmentation masks in addition to object detection.
Changes were made to core.DetectionDataset.from_pascal_voc and format.pascal_voc.load_pascal_voc_annotations.

## Type of change

Please delete options that are not relevant.

-   [+] New feature (non-breaking change which adds functionality)

## How has this change been tested, please provide a testcase or example of how you tested the change?

Via new tests.

## Any specific deployment considerations

For example, documentation changes, usability, usage/costs, secrets, etc.

## Docs

-   [ ] Docs updated? What were the changes:

2023-07-26 10:01 UTC, mayankagarwals commented on supervision/dataset/formats/pascal_voc.py
> +def polygon_to_mask(polygon: np.ndarray, resolution_wh: Tuple[int, int]) -> np.ndarray:
There is `polygon_to_mask` available in detection.utils

2023-07-28 13:09 UTC, SkalskiP commented on supervision/dataset/core.py
> +        force_masks: bool = False,
Let's add `force_masks` into the docstring below.

2023-07-28 13:10 UTC, SkalskiP commented on supervision/dataset/core.py
> +            >>> ds = sv.DetectionDataset.from_pascal_voc(
Awesome, you noticed and fixed that. 🙏🏻

2023-07-28 13:11 UTC, SkalskiP commented on supervision/dataset/core.py
> +        cls,
There is an unused import at the top of this file.

`from supervision.utils.file import list_files_with_extensions`

Please remove it if you can.

2023-07-28 13:46 UTC, SkalskiP commented
> new implementation is not compatible with v1 of load_pascal_voc_annotations, but matches the loading standard of YOLO and COCO. Shall we temporarily leave the v1 there and issue a warning, or change the implementation to be backward compatible? Is there a general rule that we follow for such cases?

@kirilllzaitsev don't worry about breaking old `load_pascal_voc_annotations`. It is a function that is not publicly exposed.

2023-07-28 22:42 UTC, kirilllzaitsev commented on supervision/dataset/formats/pascal_voc.py
> +        annotation = Detections(xyxy=xyxy, mask=masks, class_id=np.array(class_names))
The initial motivation was to temporarily introduce this inconsistency until we can identify class_id by indexing all of the classes in annotations. But now it is implemented cleaner.

2023-07-29 21:40 UTC, kirilllzaitsev commented
@SkalskiP , hi, ready for review.

2023-07-31 09:02 UTC, SkalskiP commented
Hi, @kirilllzaitsev 👋🏻! Taking a look now.

2023-07-31 10:41 UTC, SkalskiP commented
Hi, @kirilllzaitsev 👋🏻! I've done some tests, and I see some problems:

- `from_pascal_voc` loads `mask` data even if `force_masks=False.
- `mask.shape` have incorrect order of channels. It is `(N, W, H)`. It should be `(N, H, W)`.
- `mask.dtype` is incorrect. It is `uint8`. It should be `bool`.

Here is a Google Colab you can use to verify my findings: https://colab.research.google.com/drive/18rDUnAwPxhMt9YVbnFof5MS6__59NL11?usp=sharing

2023-07-31 11:02 UTC, SkalskiP requested changes

2023-07-31 11:02 UTC, SkalskiP commented on supervision/dataset/formats/pascal_voc.py
> +    # Parses polygon points in format: <polygon><x1>...</x1><y1>...</y1><x2>...</x2><y2>...</y2>...</polygon>
I think we don't need that comment, as we have unit tests.

2023-07-31 11:16 UTC, SkalskiP commented
@kirilllzaitsev let me know when you'll be ready ;)

2023-07-31 11:22 UTC, kirilllzaitsev commented
> Hi, @kirilllzaitsev 👋🏻! I've done some tests, and I see some problems:
> 
> * `from_pascal_voc` loads `mask` data even if `force_masks=False`.
> * `mask.shape` have incorrect order of channels. It is `(N, W, H)`. It should be `(N, H, W)`.
> * `mask.dtype` is incorrect. It is `uint8`. It should be `bool`.
> 
> Here is a Google Colab you can use to verify my findings: https://colab.research.google.com/drive/18rDUnAwPxhMt9YVbnFof5MS6__59NL11?usp=sharing
> 
> I'm not sure yet what to do with `force_masks`. I see there is inconsistency across different format loaders.

To me, setting the force_masks flag translates into 'masks are required, and if there are no masks - raise an error'. This is what the YOLO loader does, contrary to the COCO that uses force_masks as an indicator of whether to use masks or not. The letter seems confusing to me.

2023-07-31 11:23 UTC, kirilllzaitsev commented
@SkalskiP , ready

2023-07-31 12:32 UTC, SkalskiP commented
> To me, setting the force_masks flag translates into 'masks are required, and if there are no masks - raise an error'. This is what the YOLO loader does, contrary to the COCO that uses force_masks as an indicator of whether to use masks or not. The latter seems confusing to me.

I think that our current API sucks. `force_masks` is completely non-intuitive. And of course, this is my fault. :) I just think about how to fix it.

Things we can do:
- Keep `force_masks` but make this behavior consistent for all formats.
- Have separate methods for detection and segmentation. For example `from_coco` and `from_coco_cegemtnation`.

@hardikdava what do you think?

2023-07-31 12:42 UTC, hardikdava commented
@SkalskiP , I completely agree with you. We can introduce `sv.VisionTask` as argument to `sv.DetectionDataset` for scalable and specifying types which can be standardize.

```python
class VisionTask(Enum):
	CLASSIFICATION = 0
	OBJECT_DETECTION = 1
	ORIENTED_BOUNDING_BOX = 2
	INSTANCE_SEGMENTATION = 3
	KEYPOINTS_DETECTION = 4
	POSE_ESITMATION = 5
```
what do you think?

2023-07-31 15:48 UTC, SkalskiP requested changes

2023-07-31 15:48 UTC, SkalskiP commented on test/dataset/formats/test_pascal_voc.py
> +        with open("/tmp/test.xml", "w") as f:
@kirilllzaitsev, what are we testing here? 👇🏻 

```python
with open("/tmp/test.xml", "w") as f:
    f.write(ET.tostring(result).decode())
with open("/tmp/exptest.xml", "w") as f:
    f.write(ET.tostring(expected_result).decode())
```

2023-07-31 15:48 UTC, SkalskiP commented on test/dataset/formats/test_pascal_voc.py
> +        with open("/tmp/test.xml", "w") as f:
To be honest, I'd drop those four lines.

2023-07-31 15:48 UTC, SkalskiP commented on test/dataset/formats/test_pascal_voc.py
> +def test_detections_from_xml_obj(
I'd love to see more tests:
- Empty annotation. 
- Annotation with multiple boxes of the same class.
- Annotation with multiple boxes of different classes.

2023-07-31 15:48 UTC, SkalskiP commented on supervision/dataset/formats/pascal_voc.py
> +def load_pascal_voc_annotations_v1(
Let's drop that logic altogether.

2023-07-31 15:50 UTC, SkalskiP commented
@kirilllzaitsev I left a few more final comments. But we are definitely on the right path.

2023-07-31 22:31 UTC, SkalskiP approved these changes

2023-07-31 22:32 UTC, SkalskiP commented
Looks good to me. Merging! @kirilllzaitsev you plan to work on anything more in this release?

2023-07-31 22:33 UTC, merged

2023-08-01 06:20 UTC, kirilllzaitsev commented
@SkalskiP sure, what else is on the plate?

2023-08-01 09:00 UTC, SkalskiP commented
@kirilllzaitsev, how about splitting `DetectionDataset` into `DetectionDataset` and `SegmentationDataset` POC? https://github.com/roboflow/supervision/issues/244