Feature/redesigned annotators..... TriangleAnnotator for Multiple Annotation options
roboflow/supervision pull request #385
Opened 2023-09-29 21:02 UTC by sanaullah-code

# Triangle Annotator

For multiple options of annotation types I have added Triangle Annotator and align the text according to the triangle. Most of the time Box Annotator mixed of create a mess of annotation so we need alternate annotation option. 

List any dependencies that are required for this change.
No such dependency
## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## How has this change been tested, please provide a testcase or example of how you tested the change?

```
import cv2

IMAGE_PATH = "img.jpg"

image = cv2.imread(IMAGE_PATH)

from ultralytics import YOLO
from supervision.detection import core as c

model = YOLO('yolov8s.pt')
result = model(image, verbose=False)[0]
detections = c.Detections.from_ultralytics(result)

from supervision.detection import annotate as a
from supervision.utils import notebook as n

tri_annotator = a.TriangleAnnotator(text_scale= 5)

annotated_image = tri_annotator.annotate(image.copy(), detections=detections)

n.plot_image(image=annotated_image, size=(8, 8))

```

![test1](https://github.com/roboflow/supervision/assets/76161635/9c0ea2bb-4d0d-4a1b-84b0-5942ba9f5d8d)

![test2](https://github.com/roboflow/supervision/assets/76161635/472a5784-0dde-48dc-bcf0-125228b546ea)

![test3](https://github.com/roboflow/supervision/assets/76161635/cc7b266c-a9e7-43ee-8567-1466c26c09f9)

![test4](https://github.com/roboflow/supervision/assets/76161635/80f3c542-2f70-48f9-964a-7c450fb13702)

2023-09-29 21:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/roboflow/supervision?pullRequest=385) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/roboflow/supervision?pullRequest=385) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: onuralpszr<br/>:white_check_mark: SkalskiP<br/>:x: Sana ullah<br/><hr/>**Sana ullah** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/roboflow/supervision?pullRequest=385) it.</sub>

2023-10-02 19:15 UTC, AlainPilon commented
Shouldnt the label center align with the triangle instead of left align by default? I think it would look neater.

2023-10-02 19:52 UTC, SkalskiP commented
@sanaullah-code, could you please accept the CLA?

2023-10-02 20:02 UTC, SkalskiP requested changes

2023-10-02 20:02 UTC, SkalskiP commented on supervision/detection/annotate.py
> +            triangle_vertices = [
Can we make the triangle markers more "pointy"? Like the ones over the ball in this video? https://www.youtube.com/watch?v=QCG8QMhga9k

2023-10-02 20:07 UTC, SkalskiP commented
@sanaullah-code and @AlainPilon, I left a few comments in the code. To make the review process easier, please create a copy of this [colab](https://colab.research.google.com/drive/1iso4sYNNERe6KqH6zUixF7XwsapbCgzZ?usp=sharing) and create `TriangleAnnotator` usage example.

2023-10-02 20:09 UTC, SkalskiP requested changes

2023-10-02 20:09 UTC, SkalskiP commented on supervision/detection/annotate.py
> +            # Calculate triangle vertices based on x1, y1, x2, y2 coordinates
Please try to make the code descriptive enough, so we won't need that comment.

2023-10-02 20:09 UTC, SkalskiP commented on supervision/detection/annotate.py
> +    def __init__(
It would be awesome if we could provide some argument to regulate the size and position of the marker.

2023-10-02 20:22 UTC, SkalskiP commented on supervision/detection/annotate.py
> +class TriangleAnnotator:
Oh no... In that case. Lets keep the name :)

2023-10-02 20:26 UTC, onuralpszr commented on supervision/detection/annotate.py
> +class TriangleAnnotator:
@SkalskiP  but we can use MarkerAnnotator as base and still create those as well. so that name can be still useful

2023-10-02 20:29 UTC, onuralpszr commented
@sanaullah-code  Could you also "amend" the commit author/e-mail and use your "github" registered e-mail for fix the CLA so it can pass as well.

2023-10-02 20:52 UTC, SkalskiP commented on supervision/detection/annotate.py
> +class TriangleAnnotator:
Oh no... let's not get overexcited with inheritance. Please :)

2023-10-02 22:17 UTC, sanaullah-code commented
MarkerAnnotator or PointerAnnotator would be good.
Ok great if we don't need the label we can just put a parameters like markerheight and markerwidth which will control the size of marker and can make pointy using the parameters. 
For that CLA I don't know what is the issue 😕

2023-10-02 22:18 UTC, sanaullah-code commented
@onuralpszr I will do the changes for that CLA check to pass.

2023-10-02 22:20 UTC, onuralpszr commented
> MarkerAnnotator or PointerAnnotator would be good. Ok great if we don't need the label we can just put a parameters like markerheight and markerwidth which will control the size of marker and can make pointy using the parameters. For that CLA I don't know what is the issue 😕

Marker is too generic let's not do that. Let's use shape name in the beginning and for the name consistency let's use `TriangleMarkerAnnotator` so we can distinguish from name.

2023-10-02 22:21 UTC, onuralpszr commented
> MarkerAnnotator or PointerAnnotator would be good. Ok great if we don't need the label we can just put a parameters like markerheight and markerwidth which will control the size of marker and can make pointy using the parameters. For that CLA I don't know what is the issue 😕

Could you also add "border" around shape and controllable "thickness"

2023-10-02 22:25 UTC, sanaullah-code commented
For border we can draw a polylines around it currently the thickness is not use and we can use that.

2023-10-02 22:31 UTC, onuralpszr commented
> For border we can draw a polylines around it currently the thickness is not use and we can use that.

Or hollow polygon but bigger than filled one ? and easier to determine size as well.

2023-10-02 22:35 UTC, sanaullah-code commented
@SkalskiP and @onuralpszr I faced a issue in setting the width of the triangle
Like sometimes we have to draw a bigger triangle and sometimes small and sometimes both in one frame so we need a ratio for the width of the triangle so we draw it accordingly otherwise the triangle would same for all we go for parameterize.
Thats why I did the 1/4 of width technique which creates the triangle According to the size of object

2023-10-02 22:37 UTC, sanaullah-code commented
> > For border we can draw a polylines around it currently the thickness is not use and we can use that.
> 
> Or hollow polygon but bigger than filled one ? and easier to determine size as well.

Hollow not looks so cool we can do it or if you want I can do the both so you can check, like a HollowTriangleAnnotator?

2023-10-02 22:40 UTC, onuralpszr commented
> > > For border we can draw a polylines around it currently the thickness is not use and we can use that.
> > 
> > 
> > Or hollow polygon but bigger than filled one ? and easier to determine size as well.
> 
> Hollow not looks so cool we can do it or if you want I can do the both so you can check, like a HollowTriangleAnnotator and TriangleAnnotator?

I meant for drawing border use "hollow triangle" instead of polylines.

2023-10-02 22:45 UTC, sanaullah-code commented
> > > > For border we can draw a polylines around it currently the thickness is not use and we can use that.
> > > 
> > > 
> > > Or hollow polygon but bigger than filled one ? and easier to determine size as well.
> > 
> > 
> > Hollow not looks so cool we can do it or if you want I can do the both so you can check, like a HollowTriangleAnnotator and TriangleAnnotator?
> 
> I meant for drawing border use "hollow triangle"(you will still draw filled triangle) instead of polylines.

Done I will try it

2023-10-02 22:55 UTC, sanaullah-code commented
> @SkalskiP and @onuralpszr I faced a issue in setting the width of the triangle Like sometimes we have to draw a bigger triangle and sometimes small and sometimes both in one frame so we need a ratio for the width of the triangle so we draw it accordingly otherwise the triangle would same for all if we go for parameterize we have to this issue. Thats why I did the 1/4 of width technique which creates the triangle According to the size of object

@onuralpszr and @SkalskiP give me an oversight on it. Thank You

2023-10-03 18:03 UTC, sanaullah-code commented
@SkalskiP yes I am, last day I was traveling so couldn't do anything I will do review tonight and I will check the CLA part too.

2023-10-03 20:35 UTC, SkalskiP commented
@sanaullah-code thanks a lot! 🙏🏻

2023-10-05 10:46 UTC, SkalskiP commented
Hi @sanaullah-code 👋🏻 do you need any help from our side?

2023-10-10 23:51 UTC, SkalskiP commented
Hi once again @sanaullah-code 👋🏻 any chance you will accept CLA?

2023-12-06 11:41 UTC, SkalskiP commented
Hi @sanaullah-code, @AlainPilon, and @onuralpszr! 👋🏻 Unfortunately, I cannot merge PRs that do not have an accepted CLA. Thank you all for your comments and cooperation, but due to the above issue, I am forced to close this PR.

2023-12-06 11:41 UTC, closed without merging