faster sv.MaskAnnotator
roboflow/supervision pull request #426
Opened 2023-10-05 23:13 UTC by kapter

### Description
This PR is related to https://github.com/roboflow/supervision/issues/417
I've made some enhancements to sv.MaskAnnotator.
1. calc bgr color once for color mask creation
2. replace np.where with cv2.add operation for scene with hole and colored object

### Result 
speed up two times

2023-10-05 23:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/roboflow/supervision?pullRequest=426) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/roboflow/supervision?pullRequest=426) before we can accept your contribution.<br/><hr/>**kapter** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/roboflow/supervision?pullRequest=426) it.</sub>

2023-10-06 07:18 UTC, SkalskiP requested changes

2023-10-06 07:18 UTC, SkalskiP commented on supervision/annotators/core.py
> +        ver: str = "v1",
Please remove that extra argument.

2023-10-06 16:06 UTC, SkalskiP commented
Hi @kapter 👋🏻, I've been busy making tests of this change. Here is what I got:

1. Consistency of obtained results

- `develop`
 
  ![download - 2023-10-06T180358 646](https://github.com/roboflow/supervision/assets/26109316/2080d8ea-8485-4fe4-8a91-e2534e4d07ed)

- `kapter:Make-MaskAnnotator-faster`

  ![download - 2023-10-06T180405 617](https://github.com/roboflow/supervision/assets/26109316/45351da0-f408-42eb-b428-97d3ad48d425)

2. Drawing speed

Annotation speed depends on external factors - other processes running on the machine and varies between test runs. To validate the results, I performed 4 tests with the code in the current `develop` and 4  with the code from `kapter:Make-MaskAnnotator-faster`. I averaged the results.

- `develop`
  
  | baseline (only inference) | inference + box annotation | inference + mask annotation |
  |:-------------------------:|:--------------------------:|:---------------------------:|
  | 108 sec                   | 127 sec                    | 451 sec                     |
  | 103 sec                   | 108 sec                    | 465 sec                     |
  | 129 sec                   | 114 sec                    | 475 sec                     |
  | 128 sec                   | 127 sec                    | 476 sec                     |
  | **117 sec (average)**     | **119 sec (average)**      | **467 sec (average)**       |

  Annotation overhead: `467 - 117 = 350 `
  Per frame annotation overhead: `350 / 341 = 1.03`

- `kapter:Make-MaskAnnotator-faster`

  | baseline (only inference) | inference + box annotation | inference + mask annotation |
  |:-------------------------:|:--------------------------:|:---------------------------:|
  | 104 sec                   | 103 sec                    | 279 sec                     |
  | 99 sec                    | 98 sec                     | 296 sec                     |
  | 96 sec                    | 104 sec                    | 281 sec                     |
  | 102 sec                   | 104 sec                    | 266 sec                     |
  | **100 sec (average)**     | **102 sec (average)**      | **280 sec (average)**       |
  
  Annotation overhead: `280 - 100 = 180`
  Per frame annotation overhead: `180 / 341 = 0.52`

3. Summary:

- Results are consistent - no visual difference
- Updated `MaskAnnotator` is 0.5s per frame faster

2023-10-06 16:11 UTC, SkalskiP approved these changes

2023-10-06 16:15 UTC, SkalskiP commented
@kapter I'm curious if we can make it even faster. 🤔 💭 `0.5` sec per frame is `2x` faster than the current implementation, but it is still `0.5` sec. It is far from real-time annotation.

Having said that, I'm merging this PR. It is a clear improvement.

Maybe we could somehow sacrifice the quality of annotation to get a speed boost.

2023-10-06 16:15 UTC, merged

2023-10-09 08:34 UTC, kapter commented
I missed 
Check this please https://github.com/kapter/supervision/tree/MaskAnnotator_faster_again