Refactor class DetectionsManager to handle empty detections_all array
roboflow/supervision pull request #801
Opened 2024-01-28 16:32 UTC by KingKokouvi

This pull request addresses an issue within the vectorize function in my specific use case, where sometimes there are no detections on certain frames, leading to errors with inputs of length 0. The fix involves incorporating a pre-check for the input's length to prevent such errors from occurring.

2024-01-29 10:29 UTC, SkalskiP commented
Hi @KingKokouvi 👋🏻 ! Thanks a lot for your interest in supervision. Could you share the error message that you see when detections are empty?

2024-01-29 17:30 UTC, KingKokouvi commented
Hi, appreciate your feedback. This project is a game changer.
![error_png](https://github.com/roboflow/supervision/assets/52327882/4c100ffc-8bc2-4e83-be89-a5a5c251748f)

2024-01-30 10:11 UTC, SkalskiP requested changes

2024-01-30 10:11 UTC, SkalskiP commented on examples/traffic_analysis/inference_example.py
> +        if len(detections_all) > 0:
Looks good! Could we add `else` statement as well?

```python
if len(detections_all) > 0:
    detections_all.class_id = np.vectorize(
        lambda x: self.tracker_id_to_zone_id.get(x, -1)
    )(detections_all.tracker_id)
else:
    detections_all.class_id = np.array([], dtype=int)
```

2024-01-30 10:11 UTC, SkalskiP commented on examples/traffic_analysis/ultralytics_example.py
> +        if len(detections_all) > 0:
And the same `else` statement here.

2024-01-30 10:12 UTC, SkalskiP commented
Hi @KingKokouvi 👋🏻 ! I left small comments. Please try to add changes, and we should be ready for merge. Thanks all for catching this mistake and submitting PR! 🙏🏻

2024-01-30 11:18 UTC, SkalskiP requested changes

2024-01-30 11:18 UTC, SkalskiP commented on examples/traffic_analysis/inference_example.py
> +            (detections_all.tracker_id)
Why move it to a new line? :)

2024-01-30 11:19 UTC, KingKokouvi commented on examples/traffic_analysis/inference_example.py
> +            (detections_all.tracker_id)
it's a mistake

2024-01-30 12:08 UTC, SkalskiP approved these changes

2024-01-30 12:08 UTC, merged