'from_depthai' conversion function added
roboflow/supervision pull request #909
Opened 2024-02-15 19:14 UTC by CodeRic28

# Description

Added 'from_depthai()' function to convert depthai detection class to supervision detection class. Returns a new detections object. This can now be used in any of the supervision functions for detections or tracking.

## Dependencies
depthai

## Type of change

Please delete options that are not relevant.
-   [ ] New feature (non-breaking change which adds functionality)

## How has this change been tested, please provide a testcase or example of how you tested the change?

Initially I added this function to `venv/lib/python3.11/site-packages/supervision/detection/core.py` and used the example code to convert `depthai` detections result to `supervision` format. I then used the result to apply supervision's ByteTracker. I created a PPE detection application that used Oak-1 device for real-time detection and deployment.

## Any specific deployment considerations

No

## Docs

- No docs update

2024-02-15 19:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/roboflow/supervision?pullRequest=909) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/roboflow/supervision?pullRequest=909) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/roboflow/supervision?pullRequest=909) it.</sub>

2024-02-29 09:42 UTC, SkalskiP commented
Hi @CodeRic28 👋🏻 ! I'm very sorry for the late response. I was a bit overwhelmed with responsibilities not related to supervision.

I like the idea of adding Luxonis support. I left a few comments under your PR.

2024-02-29 09:45 UTC, SkalskiP requested changes

2024-02-29 09:45 UTC, SkalskiP commented on supervision/detection/core.py
> +    def from_depthai(cls, depthai_results) -> Detections:
Could we rename it from `from_depthai` to `from_luxonis`? I think the Luxonis brand is much more recognizable than DepthAI. To be honest, I did not know what DepthAI is, but I'm absolutely familiar with Luxonis.

2024-02-29 09:45 UTC, SkalskiP commented on supervision/detection/core.py
> +                The output Detections instance from DepthAI
Please add `.` at the end of the sentence.

2024-02-29 09:45 UTC, SkalskiP commented on supervision/detection/core.py
> +            # For device and nn setup, refer:
I'd move this to the very top of the docstring.

2024-02-29 09:45 UTC, SkalskiP commented on supervision/detection/core.py
> +        Example:
Could we make this example a bit simpler? Maybe show how it works for a single frame. For sure, drop tracker.

2026-09-09 09:27 UTC, Borda commented
@CodeRic28 thank you for your contribution; however, it seems to become stale for a very long time without much interaction on your side... so closing for now, but happy to see your next contributions 🦝

2026-09-09 09:27 UTC, closed without merging